version: "3"

services:
  ghost:
    image: ghost:4-alpine
    ports:
      - 2368:2368
    environment:
      url: http://127.0.0.1:2368
      database__client: mysql
      database__connection__host: mariadb
      database__connection__database: ghost
      database__connection__user: ghost
      database__connection__password: ${MYSQL_PASSWORD}
    depends_on:
      - mariadb
    volumes:
      - files:/var/lib/ghost/content

  mariadb:
    image: mariadb:10
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ghost
    volumes:
      - mariadb:/var/lib/mysql

  web:
    build:
      context: sapper
    environment:
      GHOST_KEY: e1b252686ec60b429aa17d742f
      GHOST_URL: http://ghost:2368/
    ports:
      - 3030:3000

volumes:
  files:
    driver: local
  mariadb:
    driver: local
