apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: iteam.se
build:
  artifacts:
    - image: iteam1337/iteam-sapper
      context: ./sapper
deploy:
  kubectl:
    manifests:
      - k8s/ghost*.yaml
      - k8s/sapper*.yaml
