apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd
  namespace: iteam-se
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: iteam-se
  name: cicd
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources:
      - deployments
      - deployments/scale
      - namespaces
      - pods
      - services
      - ingresses
      - replicasets
      - secrets
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "cicd" to read pods in the "iteam-se" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: cicd
  namespace: iteam-se
subjects:
  # You can specify more than one "subject"
  - kind: User
    name: system:serviceaccount:iteam-se:cicd
    apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: cicd # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
