# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and deploy

on:
  push:
    branches: [master]

jobs:
    cypress-run:
      runs-on: ubuntu-latest
      steps:
        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: 14
        - run: node -v
        - name: Checkout
          uses: actions/checkout@v2
        - name: Cypress run
          uses: cypress-io/github-action@v2
          with:
            command: npm run cy:run
            working-directory: sapper
            start: npm run dev
            wait-on: "http://localhost:3000"
            tag: node-14

    # This workflow contains a single job called "build"
    build-and-deploy:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - uses: actions/checkout@v2
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: install dependencies
          run: |
            curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
            chmod +x skaffold
            sudo mv skaffold /usr/local/bin
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl

        - name: create kubeconfig
          run: |
            mkdir ${HOME}/.kube
            cp k8s/config.yaml ${HOME}/.kube/config
            cd ${HOME}/.kube
            sed -i 's;$KUBE_CLUSTER_NAME;${{ secrets.KUBE_CLUSTER_NAME }};g' config
            sed -i 's;$KUBE_CLUSTER_SERVER;${{ secrets.KUBE_CLUSTER_SERVER }};g' config
            sed -i 's;$KUBE_CLUSTER_CERTIFICATE;${{ secrets.KUBE_CLUSTER_CERTIFICATE }};g' config
            sed -i 's;$KUBE_USER_NAME;${{ secrets.KUBE_USER_NAME }};g' config
            sed -i 's;$KUBE_USER_TOKEN;${{ secrets.KUBE_USER_TOKEN }};g' config
            kubectl config use-context ${{ secrets.KUBE_CLUSTER_NAME }}

        - name: build-and-deploy
          run: |
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
            skaffold run
            docker logout
