name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          command: npm run cy:run
          working-directory: sapper
          start: npm run dev
          wait-on: "http://localhost:3000"
          tag: node-14

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd sapper
          docker build -t iteam1337/iteam-sapper . --cache-from iteam1337/iteam-sapper
